Repository a-daily-diary/ADD.FE, pull requests merged in 2023-05, with the labels that each got.

#65 Color Palette 업데이트
  src/components/common/Button.tsx
  src/components/common/Tab.tsx
  src/components/diary/Diary.tsx
  src/components/diary/DiaryComment.tsx
  src/components/diary/DiaryCommentInput.tsx
  src/components/diary/DiaryComments.tsx
  src/components/diary/DiaryDetail.tsx
  src/components/diary/DiaryList.tsx
  src/components/layouts/Navbar.tsx
  src/components/layouts/header/Header.tsx
  src/components/layouts/header/HeaderRight.tsx
  src/components/profile/Empty.tsx
  src/constants/colors.ts
  src/containers/diary/DiaryCommentsContainer.tsx
  src/pages/profile/index.tsx
  src/styles/emotion.d.ts
Labels: 💄 style

#71 회원가입 페이지 > 디렉토리 구조 및 명칭 수정
  src/components/account/Email.tsx
  src/components/account/FormInput.tsx
  src/components/account/Profile.tsx
  src/components/account/Terms.tsx
  src/pages/account/register.tsx
Labels: ♻️ refactor

#76 next.config 이미지 서버 도메인 수정
  next.config.js
  src/mocks/DiaryList.tsx
Labels: ⚙️ environment

#78 ESLint rule : no-misused-promises
  .eslintrc.json
Labels: ⚙️ environment

#80 Layout 수정
  src/components/layouts/Layout.tsx
  src/pages/index.tsx
  src/pages/profile/index.tsx
Labels: 💄 style

#84 회원가입 페이지 > Terms 컴포넌트 수정
  public/images/signup/checkbox_off.png
  public/images/signup/checkbox_on.png
  src/assets/icons/checkbox_off.svg
  src/assets/icons/checkbox_on.svg
  src/components/account/RegisterTerms.tsx
  src/components/account/Terms.tsx
  src/pages/account/register.tsx
  src/types/Register.ts
Labels: ♻️ refactor, 🍱 assets, 💄 style

#87 회원가입 페이지 > Header 적용
  src/components/account/RegisterProfileImage.tsx
  src/components/diary/DiaryCommentInput.tsx
  src/components/layouts/header/Header.tsx
  src/components/layouts/header/HeaderLeft.tsx
  src/components/layouts/header/HeaderRight.tsx
  src/components/layouts/header/HeaderTitle.tsx
  src/components/layouts/header/HeaderTtitle.tsx
  src/components/layouts/header/index.ts
  src/pages/account/register.tsx
  src/pages/index.tsx
  src/styles/SVGVerticalAlignStyle.ts
Labels: ♻️ refactor, 💄 style

#88 회원가입 페이지 > input 애니메이션
  src/components/account/FormInput.tsx
  src/components/account/RegisterForm.tsx
  src/components/account/RegisterProfileImage.tsx
  src/components/account/RegisterTerms.tsx
  src/components/diary/Diary.tsx
  src/components/diary/DiaryCommentInput.tsx
  src/components/diary/DiaryComments.tsx
  src/components/layouts/header/HeaderLeft.tsx
  src/components/layouts/header/HeaderRight.tsx
  src/pages/_app.tsx
  src/styles/EllipsisStyle.ts
  src/styles/FadeInAnimationStyle.ts
  src/styles/SVGVerticalAlignStyle.ts
  src/styles/index.ts
Labels: 💄 style

#90 회원가입 페이지 > 회원가입 완료
  public/images/register/welcome.png
  src/components/account/CompleteRegister.tsx
  src/components/account/RegisterForm.tsx
  src/components/account/RegisterProfileImage.tsx
  src/pages/account/register.tsx
  src/types/Register.ts
Labels: 🐛 bug, 💄 style, ✨ feature

#68 회원가입 페이지 UI 구현
  package.json
  public/images/register/welcome.png
  src/assets/icons/checkbox_off.svg
  src/assets/icons/checkbox_on.svg
  src/assets/icons/hide_pw.svg
  src/assets/icons/select_image.svg
  src/assets/icons/show_pw.svg
  src/components/account/CompleteRegister.tsx
  src/components/account/Email.tsx
  src/components/account/FormInput.tsx
  src/components/account/RegisterForm.tsx
  src/components/account/RegisterProfileImage.tsx
  src/components/account/RegisterTerms.tsx
  src/components/common/Button.tsx
  src/components/diary/Diary.tsx
  src/components/diary/DiaryCommentInput.tsx
  src/components/diary/DiaryComments.tsx
  src/components/layouts/header/Header.tsx
  src/components/layouts/header/HeaderLeft.tsx
  src/components/layouts/header/HeaderRight.tsx
  src/components/layouts/header/HeaderTitle.tsx
  src/components/layouts/header/HeaderTtitle.tsx
  src/components/layouts/header/index.ts
  src/constants/profile.ts
  src/constants/validation/Message.ts
  src/constants/validation/Value.ts
  src/constants/validation/index.ts
  src/pages/_app.tsx
  src/pages/account/register.tsx
  src/pages/index.tsx
  src/styles/EllipsisStyle.ts
  src/styles/FadeInAnimationStyle.ts
  src/styles/GlobalStyle.ts
  src/styles/SVGVerticalAlignStyle.ts
  src/styles/index.ts
  src/styles/theme.ts
  src/types/Register.ts
  src/types/Response.ts
  yarn.lock
Labels: 🐛 bug, ♻️ refactor, 🍱 assets, 💄 style, ✨ feature, ⚙️ environment

#92 ErrorResponce message 타입 수정
  src/components/account/RegisterForm.tsx
  src/components/diary/Diary.tsx
  src/components/diary/DiaryComment.tsx
  src/components/diary/DiaryCommentInput.tsx
  src/components/diary/DiaryDetail.tsx
  src/pages/account/register.tsx
  src/types/Response.ts
  src/utils/ErrorResponseMessage.ts
  src/utils/TextareaAutosize.ts
  src/utils/index.ts
Labels: 🐛 bug

#94 로그인 페이지 구현
  src/components/account/CompleteRegister.tsx
  src/components/account/Email.tsx
  src/components/account/FormInput.tsx
  src/components/common/Button.tsx
  src/pages/account/login.tsx
  src/pages/account/register.tsx
  src/types/Login.ts
Labels: 💄 style, ✨ feature

#97 NextAuth.js 설치
  package.json
  yarn.lock
Labels: ⚙️ environment

#98 로그인 인증 구현
  src/middleware.ts
  src/pages/_app.tsx
  src/pages/account/login.tsx
  src/pages/api/auth/[...nextauth].ts
  src/types/next-auth.d.ts
Labels: ✨ feature, ⚡️ performance
