Repository a-daily-diary/ADD.FE, pull requests merged in 2023-02, with the labels that each got.

#20 @svgr/webpack 설치
  next.config.js
  package.json
  yarn.lock
Labels: ⚙️ environment

#19 Navbar 컴포넌트 생성
  next.config.js
  package.json
  src/assets/navigation/home.svg
  src/assets/navigation/matching.svg
  src/assets/navigation/profile.svg
  src/assets/navigation/write.svg
  src/components/layouts/Layout.tsx
  src/components/layouts/Navbar.tsx
  src/components/layouts/index.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/styles/emotion.d.ts
  src/styles/theme.ts
  yarn.lock
Labels: 💄 style

#22 🔧 close #21 - ESLint parserOptions에서 tsconfigRootDir 추가
  .eslintrc.json
Labels: ⚙️ environment

#27 next/image 컴포넌트 생성
  next.config.js
  src/components/common/NextImage.tsx
  src/pages/index.tsx
Labels: 💄 style

#29 ESLint rule 수정
  .eslintrc.json
Labels: ⚙️ environment

#33 로컬 폰트 폴더 위치 변경
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff2
  src/styles/theme.ts
Labels: 🍱 assets
