Repository a-daily-diary/ADD.FE, pull requests merged in 2023-03, with the labels that each got.

#26 메인 페이지 > 일기 컴포넌트 UI 구현
  next.config.js
  src/assets/icons/bookmark.svg
  src/assets/icons/bookmark_on.svg
  src/assets/icons/comment.svg
  src/assets/icons/heart.svg
  src/assets/icons/heart_on.svg
  src/assets/icons/home.svg
  src/assets/icons/matching.svg
  src/assets/icons/profile.svg
  src/assets/icons/write.svg
  src/components/common/NextImage.tsx
  src/components/diary/Diary.tsx
  src/components/diary/DiaryList.tsx
  src/components/layouts/Navbar.tsx
  src/mocks/DiaryList.tsx
  src/pages/index.tsx
  src/styles/EllipsisStyle.ts
  src/styles/GlobalStyle.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/utils/Formatter.ts
Labels: 💄 style

#37 영어 일기 쓰러가기 배너 적용
  public/images/main/banner/go_to_write.png
  src/pages/index.tsx
Labels: 🍱 assets, 💄 style

#40 getLayout을 통해 페이지 별 Navbar 적용
  src/components/layouts/Navbar.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: ♻️ refactor, 💄 style

#42 Seo 컴포넌트 생성 및 적용
  src/components/common/Seo.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: ✨ feature

#47 🔧 tsconfigRootDir 삭제
  .eslintrc.json
Labels: ⚙️ environment

#51 sr-only CSS 추가
  src/styles/ScreenReaderStyle.ts
Labels: 💄 style

#55 React Hook Form 설치
  package.json
  yarn.lock
Labels: ⚙️ environment
