Repository a-daily-diary/ADD.FE, pull requests merged in 2023-12, with the labels that each got.

#161 프로필 수정 기능 구현
  src/api/profile.ts
  src/components/diary/DiaryDetailContainer.tsx
  src/components/form/FormInput.tsx
  src/components/profile/SelectProfileImage.tsx
  src/components/profile/index.ts
  src/hooks/services/mutations/index.ts
  src/hooks/services/mutations/useEditProfile.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/profile/edit.tsx
  src/types/profile.ts
Labels: ✨ feature

#158 프로필 수정 페이지 UI
  src/api/profile.ts
  src/assets/icons/write_diary.svg
  src/components/diary/DiaryDetailContainer.tsx
  src/components/form/FormInput.tsx
  src/components/layouts/Navbar.tsx
  src/components/layouts/header/HeaderRight.tsx
  src/components/profile/SelectProfileImage.tsx
  src/components/profile/index.ts
  src/hooks/services/mutations/index.ts
  src/hooks/services/mutations/useEditProfile.ts
  src/pages/api/auth/[...nextauth].ts
  src/pages/profile/edit.tsx
  src/types/profile.ts
Labels: 💄 style

#164 랜덤 매칭 규칙 및 시작 페이지 구현
  src/assets/icons/icon_block.svg
  src/assets/icons/icon_disease.svg
  src/assets/icons/icon_en.svg
  src/assets/icons/icon_privacy.svg
  src/assets/icons/index.ts
  src/pages/matching/index.tsx
Labels: 💄 style, 👥 review

#163 모달 컴포넌트 생성 및 적용
  src/components/common/Modal.tsx
  src/components/common/index.ts
  src/constants/diary/Message.ts
  src/constants/modal/Message.ts
  src/constants/modal/index.ts
  src/constants/styles/colors.ts
  src/hooks/common/index.ts
  src/hooks/common/useBeforeLeave.ts
  src/hooks/common/useModal.ts
  src/pages/_document.tsx
  src/pages/diary/[id]/edit.tsx
  src/pages/diary/index.tsx
  src/styles/emotion.d.ts
Labels: 💄 style, ✨ feature

#167 일기 삭제, 댓글 삭제 시 삭제 확인 모달 적용
  src/components/account/RegisterProfileImage.tsx
  src/components/comment/DiaryComment.tsx
  src/components/common/Modal.tsx
  src/components/profile/SelectProfileImage.tsx
  src/constants/modal/Message.ts
  src/hooks/services/mutations/index.ts
  src/pages/diary/[id]/edit.tsx
  src/pages/diary/[id]/index.tsx
  src/pages/diary/index.tsx
Labels: ✨ feature
