Repository a-daily-diary/ADD.FE, pull requests merged in 2024-06, with the labels that each got.

#239 로그인 > 비밀번호 재설정 API 연동
  .eslintrc.json
  src/api/users.ts
  src/components/account/FindPasswordForm.tsx
  src/components/account/ResetPasswordForm.tsx
  src/constants/services/path.ts
  src/pages/account/resetPassword.tsx
  src/types/password.ts
  src/utils/index.ts
  src/utils/query.ts
Labels: ✨ feature

#253 프로필 페이지 수정 사항
  src/components/profile/ProfileLayout.tsx
  src/hooks/services/queries/useBadges.ts
  src/pages/profile/[username]/index.tsx
  src/pages/profile/index.tsx
Labels: 🐛 bug

#250 검색 기능 debounce 적용
  src/components/search/NoSearchResults.tsx
  src/components/search/RecentSearchContainer.tsx
  src/components/search/SearchHeader.tsx
  src/hooks/common/index.ts
  src/hooks/common/useDebounce.ts
  src/pages/search/[keyword].tsx
  src/pages/search/index.tsx
Labels: ⚡️ performance

#255 검색 결과에 정렬 기능 추가
  src/api/diaries.ts
  src/components/search/SearchResultHeader.tsx
  src/constants/search/index.ts
  src/constants/search/sortBy.ts
  src/hooks/services/queries/useDiaries.ts
  src/pages/search/[keyword].tsx
  src/types/diary.ts
  src/types/search.ts
Labels: ✨ feature

#257 비밀번호 재설정 페이지 URL 케밥 케이스로 변경
  src/components/account/FindPasswordForm.tsx
  src/constants/common/page.ts
  src/pages/account/find-password.tsx
  src/pages/account/reset-password.tsx
Labels: ♻️ refactor
