Repository a-daily-diary/ADD.FE, pull requests merged in 2024-02, with the labels that each got.

#177 로그인 토큰 만료 기간 동기화
  src/pages/api/auth/[...nextauth].ts
Labels: 🐛 bug

#181 [NO-ISSUE] 코드 오너 수정
  .github/CODEOWNERS
Labels: ⚙️ environment

#182 비밀번호 찾기 페이지 마크업 및 스타일링
  src/components/account/FindPasswordForm.tsx
  src/components/account/index.ts
  src/pages/account/findPassword.tsx
  src/pages/account/login.tsx
Labels: ✨ feature

#176 Loading 컴포넌트 구현
  src/assets/icons/index.ts
  src/assets/icons/loading.svg
  src/components/comment/DiaryCommentsContainer.tsx
  src/components/common/Loading.tsx
  src/components/common/index.ts
  src/components/profile/ProfileContainer.tsx
  src/constants/styles/colors.ts
  src/pages/diary/[id]/edit.tsx
  src/pages/diary/[id]/index.tsx
  src/pages/index.tsx
  src/pages/profile/index.tsx
  src/styles/RotationAnimationStyle.ts
  src/styles/emotion.d.ts
  src/styles/index.ts
Labels: ✨ feature

#174 매칭 설문 페이지 마크업 및 스타일 적용
  src/assets/icons/icon_bad.svg
  src/assets/icons/icon_english.svg
  src/assets/icons/icon_fun.svg
  src/assets/icons/icon_nice.svg
  src/assets/icons/index.ts
  src/components/matching/FeedbackTypeCheckbox.tsx
  src/pages/matching/index.tsx
  src/pages/matching/loading.tsx
  src/pages/matching/playing.tsx
  src/pages/matching/survey.tsx
  src/types/matching.ts
Labels: 🍱 assets, 💄 style, 👥 review

#187 사용자 프로필 이미지 클릭 시 프로필 페이지로 이동
  src/components/comment/DiaryComment.tsx
  src/components/diary/Diary.tsx
  src/components/diary/DiaryDetailContainer.tsx
  src/components/profile/ProfileContainer.tsx
  src/components/profile/ProfileImage.tsx
  src/components/profile/index.ts
  src/pages/profile/edit.tsx
  src/styles/GlobalStyle.ts
Labels: ✨ feature

#186 공용 Button 컴포넌트 개선
  .eslintrc.json
  src/components/account/CompleteRegister.tsx
  src/components/common/Button.tsx
  src/components/matching/RecommendTopic.tsx
  src/pages/account/findPassword.tsx
  src/pages/account/login.tsx
  src/pages/account/register.tsx
  src/pages/matching/index.tsx
  src/pages/matching/loading.tsx
  src/styles/GlobalStyle.ts
  tsconfig.json
Labels: ♻️ refactor

#189 공용 IconButton 컴포넌트 구현
  src/components/common/IconButton.tsx
  src/components/common/index.ts
Labels: ✨ feature

#193 매칭 타이머 기능 구현
  src/components/matching/MatchingController.tsx
  src/components/matching/MatchingUserInfo.tsx
  src/components/matching/RecommendTopic.tsx
  src/hooks/common/useTimer.ts
  src/pages/matching/playing.tsx
Labels: ♻️ refactor, ✨ feature

#191 로그인 > 비밀번호 찾기_링크전송완료 UI 구현
  public/images/findPassword/send_email_x2.png
  src/components/account/CompleteFindPassword.tsx
  src/components/account/FindPasswordForm.tsx
  src/components/account/index.ts
  src/pages/account/findPassword.tsx
Labels: ✨ feature
