Repository a-daily-diary/ADD.FE, pull requests merged in 2024-04, with the labels that each got.

#216 FloatingMenu 리팩토링
  src/components/comment/DiaryComment.tsx
  src/components/common/FloatingMenu.tsx
  src/components/common/Popover.tsx
  src/components/profile/ActivitiesContainer.tsx
  src/pages/diary/[id]/index.tsx
Labels: ♻️ refactor

#218 icon 파일명 통일
  src/assets/icons/bad.svg
  src/assets/icons/block.svg
  src/assets/icons/disease.svg
  src/assets/icons/en.svg
  src/assets/icons/end_of_call.svg
  src/assets/icons/english.svg
  src/assets/icons/fun.svg
  src/assets/icons/index.ts
  src/assets/icons/microphone_off.svg
  src/assets/icons/microphone_on.svg
  src/assets/icons/nice.svg
  src/assets/icons/privacy.svg
Labels: ♻️ refactor

#223 홈 > 검색창 및 최근 검색어 UI 구현
  public/images/search/search_empty.png
  src/assets/icons/close.svg
  src/assets/icons/search.svg
  src/components/layouts/header/HeaderLeft.tsx
  src/components/layouts/header/HeaderRight.tsx
  src/components/search/NoSearchResults.tsx
  src/components/search/RecentSearchContainer.tsx
  src/components/search/SearchHeader.tsx
  src/components/search/index.ts
  src/pages/search.tsx
  src/styles/GlobalStyle.ts
  src/types/search.ts
Labels: 💄 style, ✨ feature

#229 HeaderTitle 가운데 정렬 타입 추가
  src/components/layouts/header/HeaderTitle.tsx
  src/pages/account/findPassword.tsx
  src/pages/account/register.tsx
  src/pages/diary/[id]/edit.tsx
  src/pages/diary/index.tsx
  src/pages/matching/index.tsx
Labels: 💄 style

#231 배지 페이지 구현
  src/api/badges.ts
  src/api/index.ts
  src/components/badge/BadgeDetailButton.tsx
  src/components/badge/index.ts
  src/components/comment/DiaryComment.tsx
  src/components/common/AlertModal.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/Modal.tsx
  src/components/common/index.ts
  src/components/layouts/ModalLayout.tsx
  src/components/layouts/index.ts
  src/components/profile/ProfileContainer.tsx
  src/constants/common/page.ts
  src/constants/services/path.ts
  src/hooks/services/queries/index.ts
  src/hooks/services/queries/useBadges.ts
  src/pages/diary/[id]/edit.tsx
  src/pages/diary/[id]/index.tsx
  src/pages/diary/index.tsx
  src/pages/profile/[username]/badges.tsx
  src/pages/profile/[username]/index.tsx
  src/pages/profile/index.tsx
  src/types/badges.ts
Labels: ✨ feature

#222 로그인 > 비밀번호 재설정 UI 구현
  src/components/account/FindPasswordForm.tsx
  src/components/account/ResetPasswordForm.tsx
  src/components/account/index.ts
  src/pages/account/resetPassword.tsx
  src/types/password.ts
Labels: ✨ feature

#225 검색 > 최근 검색어 기능 구현
  src/components/search/RecentSearchContainer.tsx
  src/components/search/SearchHeader.tsx
  src/constants/common/index.ts
  src/constants/common/localStorage.ts
  src/constants/validation/value.ts
  src/hooks/common/index.ts
  src/hooks/common/useSearchKeywordStorage.ts
  src/pages/search.tsx
Labels: ✨ feature

#235 다른 사용자 배지 페이지 헤더 텍스트 수정
  src/pages/profile/[username]/badges.tsx
Labels: 🐛 bug
