Repository a-daily-diary/ADD.FE, pull requests merged in 2024-05, with the labels that each got.

#242 IconButton 컴포넌트 스타일 코드 리팩토링
  src/components/common/IconButton.tsx
Labels: ♻️ refactor

#227 검색 > 검색 결과 기능 구현
  next.config.js
  src/api/diaries.ts
  src/assets/icons/arrow-down.svg
  src/assets/icons/check.svg
  src/assets/icons/index.ts
  src/components/common/HighlightText.tsx
  src/components/common/index.ts
  src/components/diary/ActivityDiariesContainer.tsx
  src/components/diary/DiariesContainer.tsx
  src/components/diary/Diary.tsx
  src/components/search/RecentSearchContainer.tsx
  src/components/search/SearchHeader.tsx
  src/components/search/SearchResultHeader.tsx
  src/components/search/index.ts
  src/constants/common/page.ts
  src/hooks/services/queries/useDiaries.ts
  src/pages/search/[keyword].tsx
  src/pages/search/index.tsx
  src/types/diary.ts
Labels: ✨ feature

#238 프로필 수정 페이지 > 배지 목록 구현 및 pinned 배지 수정 기능
  src/api/badges.ts
  src/assets/icons/checkbox-circle_off.svg
  src/assets/icons/checkbox-circle_on.svg
  src/assets/icons/index.ts
  src/components/badge/BadgesContainer.tsx
  src/components/badge/index.ts
  src/hooks/services/mutations/index.ts
  src/hooks/services/mutations/useChangePinnedBadge.ts
  src/pages/profile/edit.tsx
  src/types/badges.ts
Labels: ✨ feature

#244 활동 탭 > 지난 활동 내역 중 활동/일기작성 내역이 없는 경우 UI 수정
  src/components/diary/EmptyActivitiesDiary.tsx
  src/components/profile/ActivityDetail.tsx
Labels: 💄 style

#246 Props 상수 생성
  src/constants/server/index.ts
  src/constants/server/props.ts
  src/pages/diary/[id]/edit.tsx
  src/pages/diary/[id]/index.tsx
  src/pages/index.tsx
  src/pages/profile/[username]/badges.tsx
  src/pages/profile/[username]/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
Labels: ♻️ refactor
